# Generated by Django 6.0.6 on 2026-07-04 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='annotationimage',
            index=models.Index(fields=['user', 'order'], name='annotations_user_id_53a4b7_idx'),
        ),
        migrations.AddIndex(
            model_name='polygon',
            index=models.Index(fields=['image'], name='annotations_image_i_2650b7_idx'),
        ),
    ]
